# This file for development only

version: '3.1'

services:
  # Database
  salary_hero_postgres:
    image: postgres
    container_name: salary_hero_postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASS
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./docker/init-database:/docker-entrypoint-initdb.d

  # Cache
  salary_hero_redis:
    image: redis:7.0.8
    container_name: salary_hero_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  salary_hero_zookeeper:
    container_name: salary_hero_zookeeper
    image: 'bitnami/zookeeper:3.6.2'
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # For Queue
  salary_hero_kafka:
    image: 'bitnami/kafka:2.6.0'
    container_name: salary_hero_kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:${KAFKA_PORT}
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOST}:${KAFKA_PORT}
      - KAFKA_ZOOKEEPER_CONNECT=salary_hero_zookeeper:${ZOOKEEPER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - salary_hero_zookeeper
